// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi7INQiDA3dohHmZVcDeZoCCPwZljJkq0',
    appId: '1:730778635582:web:4fe5035b41002d80af306f',
    messagingSenderId: '730778635582',
    projectId: 'advmobprog-firebase-2cba3',
    authDomain: 'advmobprog-firebase-2cba3.firebaseapp.com',
    storageBucket: 'advmobprog-firebase-2cba3.firebasestorage.app',
    measurementId: 'G-B86QYJGSJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOIr-cdLJ8EaG-rJomI3QhLpmnvkbsoBw',
    appId: '1:730778635582:android:b94ea1edbe7aae7daf306f',
    messagingSenderId: '730778635582',
    projectId: 'advmobprog-firebase-2cba3',
    storageBucket: 'advmobprog-firebase-2cba3.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1RaHHELPtywsO83u5y6R0Ny2E325bslg',
    appId: '1:730778635582:ios:7bbc0c016d334ebcaf306f',
    messagingSenderId: '730778635582',
    projectId: 'advmobprog-firebase-2cba3',
    storageBucket: 'advmobprog-firebase-2cba3.firebasestorage.app',
    iosBundleId: 'com.example.natividadMobile',
  );
}
